name: 'Wait for Vercel Preview'
description: "Wait for Vercel Deploy Preview to complete. Requires to be run on pull_request."
branding:
  icon: "clock"
  color: "blue"
inputs:
  token:
    description: "The Github Secret"
    required: true
  max_timeout:
    description: "The max time (in seconds) to run the action"
    required: false
  vercel_polling_interval:
    description: "How long (in seconds) we wait before polling the Vercel preview link again"
    required: false
  github_polling_interval:
    description: "How long (in seconds) we wait before polling Github again"
    required: false
  environment:
    description: "The name of the environment that was deployed to (e.g., staging or production)"
    required: false
  allow_inactive:
    description: "Use the most recent inactive deployment (previously deployed preview) associated with the pull request if no new deployment is available."
    required: false
outputs:
  url:
    description: "The fully qualified deploy preview URL"
runs:
  using: "node12"
  main: "index.js"
