name: 'Wait for Vercel Preview'
description: 'Wait for Vercel Deploy Preview to complete. Requires to be run on pull_request or push.'
branding:
  icon: 'clock'
  color: 'blue'
inputs:
  token:
    description: 'The Github Secret'
    required: true
  max_timeout:
    description: 'The max time to run the action'
    required: false
  environment:
    description: 'The name of the environment that was deployed to (e.g., staging or production)'
    required: false
  allow_inactive:
    description: 'Use the most recent inactive deployment (previously deployed preview) associated with the pull request if no new deployment is available.'
    required: false
  check_interval:
    description: 'How often (in seconds) should we make the HTTP request checking to see if the deployment is available?'
    default: '2'
    required: false
  vercel_password:
    description: 'Vercel password protection secret'
    required: false
  vercel_protection_bypass_header:
    description: 'Vercel protection bypass for automation'
    required: false
  basic_auth_credentials_base64:
    description: 'In case the app is protected with Basic Auth, provide base64 encoded credentials in form `username:password`'
    required: false
  skip_health_check:
    default: 'false'
    description: 'Skip health check for status code 200 after deployment'
    required: false
  path:
    description: 'The path to check. Defaults to the index of the domain'
    default: '/'
    required: false

outputs:
  url:
    description: 'The fully qualified deploy preview URL'
  vercel_jwt:
    description: 'If the deployment is using password protection, this will be a JWT. Otherwise, outputs an empty string'
runs:
  using: 'node20'
  main: 'dist/index.js'
